apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: namespaces-network-policy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaces-network-policy
subjects:
- kind: ServiceAccount
  name: namespaces-network-policy
  namespace: ops
