apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: namespaces-network-policy
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list","watch","patch"]
- apiGroups: ["extensions", "apps"]
  resources: ["networkpolicies"]
  verbs: ["create","get"]
